In [1]:
#### 1. Import the numpy package under the name `np`
import numpy as np

In [3]:
#### 2. Create a null vector of size 10 

null_vector = np.zeros((10))  
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
#### 3. Create a null vector of size 10 but the fifth value which is 1

null_vector = np.zeros(10)
null_vector[4] = 1
null_vector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [7]:
#### 4. Create a vector with values ranging from 10 to 49

vector = np.arange(10, 50)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [13]:
#### 5. Create a 3x3 matrix with values ranging from 0 to 8

matrix = np.arange(0,9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:
#### 6. Find indices of non-zero elements from [1,2,0,0,4,0]

array = [1,2,0,0,4,0]
non_zero = np.nonzero(array)
non_zero      

array([0, 1, 4])

In [35]:
#### 7. Create a 3x3 identity matrix

identity_matrix = np.eye(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
#### 8. Create a 3x3x3 array with random values

random_array = np.random.rand(3,3,3)
random_array

array([[[0.77729948, 0.70559435, 0.23490299],
        [0.85688545, 0.00260271, 0.86811465],
        [0.44057045, 0.84269723, 0.39191402]],

       [[0.93825331, 0.23166929, 0.53066202],
        [0.8867533 , 0.4806384 , 0.45134197],
        [0.93967436, 0.43720157, 0.68416909]],

       [[0.10796383, 0.71147432, 0.96294588],
        [0.93856727, 0.04565385, 0.6505025 ],
        [0.51883777, 0.93517555, 0.70630935]]])

In [41]:
#### 9. Create a 10x10 array with random values and find the minimum and maximum values

random_10 = np.random.rand(10, 10)
min = random_10.min()
max = random_10.max()
min, max

(0.007362489479107892, 0.9979039696947914)

In [55]:
#### 10. Create a random vector of size 30 and find the mean value 

random_vector = np.random.rand(30)
mean = random_vector.mean()
mean

0.5121367747596629

In [43]:
#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal # numpy.diag(v, k=0) Extract a diagonal or construct a diagonal array.

values = np.array([1, 2, 3, 4, 5])
matrix = np.diag(values, k=-1)                         #k= which daigonal? 
matrix

array([[0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0]])

In [23]:
#### 12. Normalize a 5x5 random matrix: hint: (x -mean)/std`

matrix = np.random.rand(5,5)
matrix
mean = matrix.mean()
std = matrix.std()
normalized_matrix = (matrix - mean) / std
normalized_matrix

array([[ 0.99761302, -0.87167389,  0.79624804, -0.15668927,  1.28622149],
       [ 0.88633486, -1.49425386, -1.05952276,  0.01039544,  1.20347557],
       [-1.3809952 ,  0.43616659,  0.84025416, -0.45239432, -0.96240594],
       [ 0.50017329,  1.1660695 , -0.54937214,  1.42925368,  1.4036413 ],
       [ 0.10094134, -1.69229151, -0.65794081, -1.43452061, -0.34472798]])

In [79]:
#### 13. How to find common values between two arrays?   hint: np.intersect1d`

array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([4, 5, 6, 7, 8])
common_values = np.intersect1d(array1, array2)
common_values

array([4, 5])

In [83]:
#### 14. Create a random vector of size 10 and sort it 

random_vector = np.random.rand(10)
sorted_vector = np.sort(random_vector)
sorted_vector

array([0.06617177, 0.11253898, 0.18846291, 0.50164153, 0.61608721,
       0.63370092, 0.64305414, 0.73121829, 0.79908695, 0.86066886])

In [49]:
#### 15. Create random vector of size 10 and replace the maximum value by 0

random_vector = np.random.random(10)
max = random_vector.max()
random_vector[random_vector.argmax()] = 0
random_vector

array([0.78735757, 0.        , 0.41007268, 0.6725307 , 0.76775859,
       0.93451941, 0.31625282, 0.78480758, 0.30243852, 0.4783209 ])

In [51]:
#### 16. Subtract the mean of each row of a matrix   hint: mean(axis=,keepdims=True)`keepdimension

matrix = np.random.rand(5,5)
mean_sub = matrix - matrix.mean(axis=1, keepdims=True)
mean_sub

array([[-0.14411013, -0.00887544,  0.08728909, -0.33336938,  0.39906586],
       [ 0.48087591, -0.06365339,  0.20455702, -0.41106156, -0.21071798],
       [-0.2510148 , -0.09509953,  0.13945515,  0.27617229, -0.06951311],
       [ 0.25970921,  0.13133048,  0.05771722, -0.15177817, -0.29697875],
       [-0.5032326 ,  0.04901762,  0.01986644,  0.21815188,  0.21619666]])

In [57]:
#### 17. How to get the n largest values of an array: hint: np.argsort(sort values) | np.argpartition

np.random.seed(42)
array = np.arange(10000)
np.random.shuffle(array)
n = 5                        # 5 largest values
#indices = np.argpartition(array, -n)[-n:]
#n_largest_values = array[indices]

indices = array[np.argsort(array)][-n:]    #could also use np.sort [-n:]
indices

array([9995, 9996, 9997, 9998, 9999])

In [71]:
#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) hint: np.where`


random_matrix = np.arange(15).reshape(5,3)
print(random_matrix)
random_matrix_new = np.where(random_matrix > 4, np.square(random_matrix), random_matrix)
random_matrix_new

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


array([[  0,   1,   2],
       [  3,   4,  25],
       [ 36,  49,  64],
       [ 81, 100, 121],
       [144, 169, 196]])